# Site settings
title: Alex De Marco
author: Alex De Marco
email: alex6152@gmail.com
description: I'm a software engineer in the New York City area. This is my web page.
copyright: Copyright &copy; 2014 Alex De Marco. All rights reserved.
baseurl: ""
url: "http://www.alexdemarco.com"
twitter_username: alexdemarco2 
github_username:  alexdm

# Build settings
markdown: kramdown
